### ISSUE TITLE
CSS breaks Lumo dark mode

### ISSUE THREAD

**Issue by stefanuebe** [samie/Idle#10]
The idle.css defines a different background color than the default one of the lumo dark theme. This leads to a white-ish background, when using the dark theme. 

Not sure if the addon should apply these styles at all. In most applications, the background color is defined by a global styling, therefore I would leave that part out. Also adding bg color transitions might be seen as some unwanted style injection :)

If someone wants to have stylings based on the state, they can easily add these using the given css class names.

<img width="1272" alt="image" src="https://github.com/user-attachments/assets/af992bd2-12f4-494b-acfc-3ff0ed019090">

**Comment by stefanuebe** [comment]
Workaround: 
```css
body.useractive,
body.userinactive {
	background-color: var(--lumo-base-color);
	transition: background-color 0s;
}
```
